version: "2"
services:
  backend:
    container_name: backend
    restart: always
    build: ./server-mongodb/
    volumes:
      - ./server-mongodb:/usr/src/app/server-mongodb
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.6.3
    volumes:
      - ./dataDocker:/dataDocker/db
    ports:
      - "27017:27017"
  client:
    container_name: client
    restart: always
    build: ./client/
    volumes:
      - ./client:/usr/src/app/client
    depends_on:
      - backend
    ports:
      - "3000:3000"
